sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y build-dep xen
  - sudo apt-get -y install python python-dev python-twisted
  - wget http://bits.xensource.com/oss-xen/release/4.5.2/xen-4.5.2.tar.gz
  - tar -xvf xen-4.5.2.tar.gz 
install:
  - pushd xen-4.5.2/
  - ./configure
  - make dist-xen
  - make dist-tools  
  - popd

