sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y build-dep xen
  - sudo apt-get -y install libyajl-dev
  - sudo apt-get -y install guilt
  - wget http://bits.xensource.com/oss-xen/release/4.6.1/xen-4.6.1.tar.gz
  - tar -xvf xen-4.6.1.tar.gz 
install:
  - pushd xen-4.6.1/
  - ./configure
  - make dist-xen
  - make dist-tools  
  - popd
script:
  - exit 0

