sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y build-dep xen
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install bcc bin86 gawk bridge-utils iproute libcurl3 libcurl4-openssl-dev bzip2 module-init-tools transfig tgif 
  - sudo apt-get -y install texinfo texlive-latex-base texlive-latex-recommended texlive-fonts-extra texlive-fonts-recommended pciutils-dev mercurial
  - sudo apt-get -y install make gcc libc6-dev zlib1g-dev python python-dev python-twisted libncurses5-dev patch libvncserver-dev libsdl-dev libjpeg62-dev
  - sudo apt-get -y install iasl libbz2-dev e2fslibs-dev git-core uuid-dev ocaml ocaml-findlib libx11-dev bison flex xz-utils libyajl-dev
  - sudo apt-get -y install gettext libpixman-1-dev libaio-dev markdown pandoc  
  - wget http://bits.xensource.com/oss-xen/release/4.5.2/xen-4.5.2.tar.gz
  - tar -xvf xen-4.5.2.tar.gz 
install:
  - pushd xen-4.5.2/
  - ./configure
  - make dist-xen
  - make dist-tools  
  - popd
script:
  - exit 0

